"""add completed flag to performance table

Revision ID: fe01ca7b760d
Revises: 6f74c13dc594
Create Date: 2020-07-16 19:57:40.830614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe01ca7b760d'
down_revision = '6f74c13dc594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'completed')
    # ### end Alembic commands ###
